<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    


    <script>



        // fetch('https://jsonplaceholder.typicode.com/users')
        //         .then((response) => response.json())
        //         .then((json) => console.log(json));


        //         console.log('END *******');




        console.log('END *******');

        /*
        Breakdown of process above ***
        Fetch initiates a network request
        Fetch returns a promise
        When the promise resolves weget an abj (success, failure, etc.. )

        To access the actual data we then parse the response body
        For that we use response.json()

        json() also returns a promise that we "then" access to get the parsed json data.

        


        */

        // const url2 = 'https://glorpborgdorkhorp.org/'
        // fetch(url2)
        // .then((response) => response.json())
        // .then((json) => console.log(json))
        // .catch((error) => {
        //     console.log(error)
        // })


        /*
        The catch() method is used to handle ny errors that could occur during the fetch operation
        It's good practice to always include a catch() block to avoid unhandled errors
        */

        /*
        then() and async/await are 2 different ways to handle promises in JaveScript

        PROMISES ASYNC/AWAIT

        Promises can be trick!
        Imagine you have to load lots of data:
        Get current user
        Get notifications
        Get posts from subscribed acounts
        */

        /*
        Async/Await is a syntetic feature om js that allows you to write asynchronoumus in a more readable way
        */

        async function getData() {
            const result = await fetch('https://jsonplaceholder.typicode.com/users');
            const data = await result.json();
            console.log(data)          
        }
        getData()

        /*
        The await keyword is used inside an async function to pause the execution until a promise is resolved/rejected
        We cannot use await outside of an async function
        */

        async function test() {
            return 2;
        }
        console.log(test())

        // Async function always returns a promise regardless of whether you return a value or not

        /*
        ERROR HANDLING ASYNC/AWAIT
        In this context we use a try... catch block
        */

        async function fetchData() {
            try {
                // Attemp to fetch data from an API
                const response = await fetch('https://jsonplaceholder.typicode.com/todos/1');

                const data = await response.json()
                console.log(data)

            } catch(error) {
                console.error('Error fetching data: ', error)
            }
        }
        fetchData();
    </script>
</body>
</html>